pojawiator_sampel=0
collected=0
stream=0
efektuj=0
efekciaruj=0

// USTAW TE ZMIENNE - JAKI ETAP MA ODBLOKOWAC NA MAPIE, WLACZ WARTOSC ODBLOKOWANIA NA MAPIE i USTAW ZMIENNA KTORA DAJE ZNAC ZE ZOSTALO ZDOBYTE
// GDY MARIO SKUSI TE WARTOSCI SIE ZERUJA

/*

unlock=100196


/* */
/*  */
